document.addEventListener("DOMContentLoaded", function() {

    async function initWidget() {
        const statusDiv = document.getElementById('latest-val');
        const subTitle = document.querySelector('.simulation-stage p');
        
        try {
            // 1. Fetch the static JSON file (generated by Python)
            const response = await fetch('./streamflow.json');
            if (!response.ok) throw new Error("File not found");
            
            const data = await response.json();

            // 2. Check for the specific error flag we set in Python
            if (data.error) {
                statusDiv.innerText = "Ice / Unavailable";
                statusDiv.style.color = "#94a3b8";
                return;
            }

            // 3. Extract Metadata (Type & Unit)
            const type = data._meta ? data._meta.type : "Discharge";
            const unit = data._meta ? data._meta.unit : "cfs";

            // 4. Parse the points
            const timeSeries = data.value.timeSeries[0].values[0].value;
            const chartData = timeSeries.map(point => ({
                x: new Date(point.dateTime),
                y: parseFloat(point.value)
            }));

            if (chartData.length === 0) {
                statusDiv.innerText = "No Data";
                return;
            }

            // 5. Update Text
            const latestVal = chartData[chartData.length - 1].y;
            statusDiv.innerHTML = `${latestVal} <span style="font-size: 0.6em;">${unit}</span>`;
            statusDiv.style.color = '#38bdf8';
            
            // Update the subtitle
            if(subTitle) subTitle.innerText = `USGS 04234000 • ${type} • Past 7 Days`;

            // 6. Render
            renderChart(chartData, type, unit);

        } catch (error) {
            console.error("Widget Error:", error);
            statusDiv.innerText = "Offline";
            statusDiv.style.color = "#ef4444";
        }
    }

    function renderChart(chartData, label, unit) {
        const ctx = document.getElementById('flowChart').getContext('2d');
        
        if (window.myFlowChart) window.myFlowChart.destroy();

        const gradient = ctx.createLinearGradient(0, 0, 0, 300);
        gradient.addColorStop(0, 'rgba(56, 189, 248, 0.4)'); 
        gradient.addColorStop(1, 'rgba(56, 189, 248, 0.0)'); 

        window.myFlowChart = new Chart(ctx, {
            type: 'line',
            data: {
                datasets: [{
                    label: label,
                    data: chartData,
                    borderColor: '#38bdf8',
                    backgroundColor: gradient,
                    borderWidth: 2,
                    pointRadius: 0,
                    pointHoverRadius: 6,
                    fill: true,
                    tension: 0.1
                }]
            },
            options: {
                responsive: true,
                maintainAspectRatio: false,
                plugins: {
                    legend: { display: false },
                    tooltip: {
                        mode: 'index',
                        intersect: false,
                        backgroundColor: 'rgba(15, 23, 42, 0.9)',
                        titleColor: '#f8fafc',
                        bodyColor: '#38bdf8',
                        borderColor: '#334155',
                        borderWidth: 1,
                        callbacks: {
                            label: function(context) {
                                return `${context.parsed.y} ${unit}`;
                            }
                        }
                    }
                },
                scales: {
                    x: {
                        type: 'time',
                        time: {
                            unit: 'day',
                            displayFormats: { day: 'MMM d' }
                        },
                        grid: { display: false },
                        ticks: { color: '#94a3b8', maxRotation: 0, autoSkip: true }
                    },
                    y: {
                        grid: { color: '#334155', borderDash: [5, 5] },
                        ticks: { color: '#94a3b8' }
                    }
                }
            }
        });
    }

    initWidget();
});